name: run-notebook

on:
  workflow_run:
    workflows: ["JSON check"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Make People.html
      run: jupyter nbconvert people.ipynb --execute
      
    - name: Create site
      run: |
        mkdir -p public
        mv People.html public

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    
